---
- hosts: php
  vars:
    mysql_root_password: 123456
  tasks:
  - name: Instala MySQL
    apt:
	name: {{ item }}
    	state: present
    	sudo: yes
    with_items:
	- mysql-server

  - name: Inicia servicios de MySQL
    sudo: yes
    service:
      name: mysql
      state: started
      enabled: true

  - name: Actualiza credenciales de root
    sudo: yes
    mysql_user:
      name: root
      host: "{{ item }}"
      password: "{{ mysql_root_password }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
    with_items:
	- "{{ ansible_hostname }}"
	- 127.0.0.1
	- ::1
	- localhost
